###############################################################################
#  A set of template files to organize projects with a single Makefile
#  Copyright (C) 2013 Zhongming Qu <qzmfrank@umich.edu>
#  
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.  
###############################################################################
#	Welcome! The comments in this file will guide you through the process.
#  Please read all the comments very carefully before changing anything.
#  	The idea of this set of template files (Makefile, Makefile.vars, and
#  all the makevars.mk) aim to help organize any C/C++ project with a single
#  Makefile. The advantage is speed. The usual drawback are bad maintainence
#  and modularity. This set of files attempt to cut down all the repetitive
#  work that are usually done manually, i.e., listing target-prerequisites
#  while preserving almost the same degree of modularity as the recursive
#  make approach.
#  	If you have any suggestions and/or ideas, please let me know.
###############################################################################
#				STEP 1
#DIRECTORY NAME FROM THE ROOT DIRECTORY
#  Be very careful:
# 	NO SPACE ( tab is OK )
# 	NO DEFERRED-EVALUATION ( always use colon-equal, i.e., := ) #
DIR003		:=src/file-io# Please, NO SPACE 
###############################################################################
#				STEP 2
#DIRECTORY-SPECIFIC SOURCE FILES
#  	Remember to add the ${DIR003}/ to whatever source files(s) you wish to add.
#  The dependencies are automatically resolved by the dependency files (*.d 
#  files) generated by the compiler through the -MD -MP and/or similar options.
#  Note that:
#  	a) The GNU make does NOT support recursive include directive. So we must
#  NOT include any *.d file in this file. All the *.d files are included in the
#  Makefile in the root directory AFTER all the makevars.mk's are include.
#  	b) So far, only supports C/C++ files. Maybe Fortran support is needed TODO
#  	c) Please refrain from using $(wildcard) command. It only helps when not
#  really nessaccery and complicates the situation when we have forgotten about
#  it. Yes, be explicit. Manually list all the source files here.
#  	d) Dependencies are readily dealt with by the setup of the Makefile. One
#  NEVER needs to specify the dependency for any .o file.
${DIR003}CFILES		:=	${DIR003}/file-io.c
${DIR003}CPPFILES	:=
################## DO NOT MODIFY ################
${DIR003}OBJFILES	:=	${${DIR003}CPPFILES:${DIR003}%.cpp=${BUILD}%.o}	\
				${${DIR003}CFILES:${DIR003}%.c=${BUILD}%.o}
${DIR003}DEPFILES	:=	${${DIR003}OBJFILES:%.o=%.d}
${DIR003}ASMFILES	:=	${${DIR003}OBJFILES:${BUILD}%.o=${DEBUG}%.s}
################## DO NOT MODIFY ################ 
###############################################################################
#				STEP 3
#DIRECTORY-SPECIFIC BINARY FILES
#	Executables listed in ${DIR}BINFILES are considered the final output of
#  this project. All of them should be built into ${BIN} instead of ${BUILD}
#  for all other executables. 
#  	So far, only supports CPP source files. TODO
${DIR003}BIN	:=		mshtodat
################## DO NOT MODIFY ################
${DIR003}BINCPP	:=		${${DIR003}BIN:%=${DIR003}/%.cpp}
${DIR003}BINOBJ	:=		${${DIR003}BINCPP:${DIR003}%.cpp=${BUILD}%.o}
${DIR003}BINDEP	:=		${${DIR003}BINOBJ:%.o=%.d}
${DIR003}BINEXE	:=		${${DIR003}BINOBJ:${BUILD}%.o=${BIN}%.exe}
${DIR003}BINASM	:=		${${DIR003}BINOBJ:${BUILD}%.o=${DEBUG}%.s}
################## DO NOT MODIFY ################
#  The default build rule for ${DIR003}BINEXE is:
#${${DIR003}BINEXE}: ${${DIR003}BINOBJ} ${${DIR003}OBJFILES} 
#  Comment the above line and specify your own rules here:
#  Note that we can take advantage of the following pattern rule:
#		rule ${BIN}/%.exe: ${BUILD}/%.o
${BIN}/mshtodat.exe: ${BUILD}/mshtodat.o ${BUILD}/file-io.o 
###############################################################################
#				STEP 4
#DIRECTORY-SPECIFIC TEST FILES
#	Speicify all the test files. All test files must be CPP files. But when
#  listing the them in ${DIR003}TST, do NOT write the .cpp extension. For example:
#  if one wishes to add test-mytest.cpp, he should write:
#
#  		${DIR003}TST:=test-mytest
#
${DIR003}TST	:=		test-file-io
################## DO NOT MODIFY ################
${DIR003}TSTCPP	:=		${${DIR003}TST:%=${DIR003}/%.cpp}
${DIR003}TSTOBJ	:=		${${DIR003}TSTCPP:${DIR003}%.cpp=${BUILD}%.o}
${DIR003}TSTDEP	:=		${${DIR003}TSTOBJ:%.o=%.d}
${DIR003}TSTEXE	:=		${${DIR003}TSTOBJ:%.o=%.exe}
${DIR003}TSTASM	:=		${${DIR003}TSTOBJ:${BUILD}%.o=${DEBUG}%.s}
SRCFILES	:=		${SRCFILES} ${${DIR003}CFILES} ${${DIR003}CPPFILES} ${${DIR003}TSTCPP} ${${DIR003}BINCPP}
DEPFILES	:=		${DEPFILES} ${${DIR003}DEPFILES} ${${DIR003}TSTDEP} ${${DIR003}BINDEP}
################## DO NOT MODIFY ################
#  The default build rule for ${DIR003}BINEXE is:
${${DIR003}TSTEXE}: ${${DIR003}TSTOBJ} ${${DIR003}OBJFILES} 
#  This is using all the object files generated in this directory plus the
#  object files of the test CPP files. In case where this is either not enough
#  or too much, please modify the following line.
#  Comment the default build rule and specify your own rules here:
#  Note that we can take advantage of the following pattern rule:
#		rule ${BIN}/%.exe: ${BUILD}/%.o
${BIN}/mshtodat.exe: ${BUILD}/mshtodat.o ${BUILD}/file-io.o 
###############################################################################
#				STEP 5
#DIRECTORY-SPECIFIC COMPILING AND LINKING OPTIONS
#	Options specified here are used in this directory. By default, all 
#  builds use the same options. When different compiling and/or linking options 
#  need to be assigned to different targets, the programmer needs to list all
#  the speical target-prerequisite dependencies manually.
#  	By default, the local options inherits the corresponding global ones 
#  from the makevars.mk in the root directory. If one wishes to add any 
#  additional options that are specific to this very directory, add them after 
#  the global ones. For example:
# 	 	${DIR003}CFLAGS	:=${CFLAGS} [directory-specific options]
#  	Usually, ${DIR003}INCS and ${DIR003}LIBS should not need to be modified if
#  the build in this directory does not require some extra libraries and/or 
#  hearder files. But in case it did, free at ease to modify these two 
#  variables.
${DIR003}CFLAGS 	:=${CFLAGS}
${DIR003}CXXFLAGS	:=${CXXFLAGS}
${DIR003}INCS		:=${INCS}
${DIR003}LIBS		:=${LIBS} 
###############################################################################
#				STEP 7
#	Write whatever dependencies here:



###############################################################################
###############################################################################
###############################################################################
#	Congratulations! You have completed everything you need to do to build
#  this directory. You do not need to modify this file unless some C and/or
#  CPP source files are added, removed, or renamed. In that case, just go over
#  STEP 1-6 again and it is done!
###############################################################################
###############################################################################
###############################################################################
#				WANRING
#  Please do not modify the following part if you are not 100% sure about it.
#  The design of this file is that one only needs to modify the part above.
#  If you find you need to modify any of the parts below, be very careful!
#				WANRING
###############################################################################
###############################################################################
############################################################################### 
#DIR003ECTORY-SPECIFIC PATTERN RULES
#  C++ linkage at the top level
${BIN}/%.exe: ${BUILD}/%.o 
	@echo Linking  "${B_RED}$@${NONE}"...
	@${CXX} -o $@ ${filter %.o,$^} ${${DIR003}LIBS} 
${BUILD}/%.exe: ${BUILD}/%.o 
	@echo Linking  "${RED}$@${NONE}"...
	@${CXX} -o $@ ${filter %.o,$^} ${${DIR003}LIBS} 
#  C++ sources
${BUILD}/%.o: ${DIR003}/%.cpp
	@echo Compiling "${MAGENTA}$@${NONE}"...
	@${CXX} -o $@ -c $< ${${DIR003}CXXFLAGS} ${${DIR003}INCS}
${DEBUG}/%.s: ${DIR003}/%.cpp
	@echo Generating "${CYAN}$@${NONE}"...
	@${CXX} -o $@ $< ${ASMFLAGS} ${${DIR003}CXXFLAGS} ${${DIR003}INCS} 
#  C sources
${BUILD}/%.o: ${DIR003}/%.c
	@echo Compiling "${MAGENTA}$@${NONE}"...
	@${CC} -o $@ -c $< ${${DIR003}CFLAGS} ${${DIR003}INCS}
${DEBUG}/%.s: ${DIR003}/%.c
	@echo Generating "${CYAN}$@${NONE}"...
	@${CC} -o $@ $< ${ASMFLAGS} ${${DIR003}CFLAGS} ${${DIR003}INCS} 
#DIR003ECTORY-SPECIFIC PHONY TARGETS
.PHONY: ${DIR003}-all ${DIR003}-test ${DIR003}-asm ${DIR003}-list
TARGET_ALL	:=${TARGET_ALL} ${DIR003}-all
TARGET_TEST	:=${TARGET_TEST} ${DIR003}-test
TARGET_ASM	:=${TARGET_ASM} ${DIR003}-asm
TARGET_LIST	:=${TARGET_LIST} ${DIR003}-list
${DIR003}-all: ${${DIR003}OBJFILES} ${${DIR003}BINEXE}
	@echo Finished building "${B_BLUE}$@${NONE}".
${DIR003}-test: ${${DIR003}TSTEXE}
	@echo Finished building "${B_BLUE}$@${NONE}".  
${DIR003}-asm: ${${DIR003}ASMFILES} ${${DIR003}TSTASM}
	@echo Finished generating "${B_BLUE}$@${NONE}".  
${DIR003}-list:
	@echo \#\#\#\#\#\#\#\#"${B_BROWN}BEGIN $@${NONE}"\#\#\#\#\#\#\#\#
	@echo "${BROWN}CFILES${NONE}":${${DIR003}CFILES}
	@echo "${BROWN}CPPFILES${NONE}":${${DIR003}CPPFILES}
	@echo "${BROWN}OBJFILES${NONE}":${${DIR003}OBJFILES}
	@echo "${BROWN}DEPFILES${NONE}":${${DIR003}DEPFILES}
	@echo "${BROWN}ASMFILES${NONE}":${${DIR003}ASMFILES}
	@echo "${BROWN}TSTCPP${NONE}":${${DIR003}TSTCPP}
	@echo "${BROWN}TSTOBJ${NONE}":${${DIR003}TSTOBJ}
	@echo "${BROWN}TSTDEP${NONE}":${${DIR003}TSTDEP}
	@echo "${BROWN}TSTEXE${NONE}":${${DIR003}TSTEXE}
	@echo "${BROWN}TSTASM${NONE}":${${DIR003}TSTASM} 
	@echo "${BROWN}BINCPP${NONE}":${${DIR003}BINCPP}
	@echo "${BROWN}BINOBJ${NONE}":${${DIR003}BINOBJ}
	@echo "${BROWN}BINDEP${NONE}":${${DIR003}BINDEP}
	@echo "${BROWN}BINEXE${NONE}":${${DIR003}BINEXE}
	@echo "${BROWN}BINASM${NONE}":${${DIR003}BINASM} 
	@echo \#\#\#\#\#\#\#\#"${B_BROWN}END $@${NONE}"\#\#\#\#\#\#\#\#
