CFLAGS 	:=-Wno-deprecated
include ../makevars.mk
###############################################################################
-include ${DEPFILES}
###############################################################################
test.exe: test.o DunavantRule.o WandzuraRule.o GaussQuadratures.o
