###############################################################################
#  A set of template files to organize projects with a single Makefile
#  Copyright (C) 2013 Zhongming Qu <qzmfrank@umich.edu>
#  
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.  
###############################################################################
#	Welcome! The comments in this file will guide you through the process.
#  Please read all the comments very carefully before changing anything.
#  	The idea of this set of template files (Makefile, Makefile.vars, and
#  all the makevars.mk) aim to help organize any C/C++ project with a single
#  Makefile. The advantage is speed. The usual drawback are bad maintainence
#  and modularity. This set of files attempt to cut down all the repetitive
#  work that are usually done manually, i.e., listing target-prerequisites
#  while preserving almost the same degree of modularity as the recursive
#  make approach.
#  	If you have any suggestions and/or ideas, please let me know.
###############################################################################
#				STEP 1
#DIRECTORY NAME FROM THE ROOT DIRECTORY
#  Be very careful:
# 	NO SPACE ( tab is OK )
# 	NO DEFERRED-EVALUATION ( always use colon-equal, i.e., := ) #
DIR-mem-bw		:=src/mem-bw# Please, NO SPACE 
###############################################################################
#				STEP 2
#DIRECTORY-SPECIFIC SOURCE FILES
#  	Remember to add the ${DIR-mem-bw}/ to whatever source files(s) you wish to add.
#  The dependencies are automatically resolved by the dependency files (*.d 
#  files) generated by the compiler through the -MD -MP and/or similar options.
#  Note that:
#  	a) The GNU make does NOT support recursive include directive. So we must
#  NOT include any *.d file in this file. All the *.d files are included in the
#  Makefile in the root directory AFTER all the makevars.mk's are include.
#  	b) So far, only supports C/C++ files. Maybe Fortran support is needed TODO
#  	c) Please refrain from using $(wildcard) command. It only helps when not
#  really nessaccery and complicates the situation when we have forgotten about
#  it. Yes, be explicit. Manually list all the source files here.
#  	d) Dependencies are readily dealt with by the setup of the Makefile. One
#  NEVER needs to specify the dependency for any .o file.
${DIR-mem-bw}CFILES	:=
${DIR-mem-bw}CPPFILES	:=	${DIR-mem-bw}/sumcopy.cpp
################## DO NOT MODIFY ################
${DIR-mem-bw}OBJFILES	:=	${${DIR-mem-bw}CPPFILES:${DIR-mem-bw}%.cpp=${BUILD}%.o}	\
				${${DIR-mem-bw}CFILES:${DIR-mem-bw}%.c=${BUILD}%.o}
${DIR-mem-bw}DEPFILES	:=	${${DIR-mem-bw}OBJFILES:%.o=%.d}
${DIR-mem-bw}ASMFILES	:=	${${DIR-mem-bw}OBJFILES:${BUILD}%.o=${DEBUG}%.s}
################## DO NOT MODIFY ################ 
###############################################################################
#				STEP 3
#DIRECTORY-SPECIFIC BINARY FILES
#	Executables listed in ${DIR}BINFILES are considered the final output of
#  this project. All of them should be built into ${BIN} instead of ${BUILD}
#  for all other executables. 
#  	So far, only supports CPP source files. TODO
${DIR-mem-bw}BIN	:=		
################## DO NOT MODIFY ################
${DIR-mem-bw}BINCPP	:=		${${DIR-mem-bw}BIN:%=${DIR-mem-bw}/%.cpp}
${DIR-mem-bw}BINOBJ	:=		${${DIR-mem-bw}BINCPP:${DIR-mem-bw}%.cpp=${BUILD}%.o}
${DIR-mem-bw}BINDEP	:=		${${DIR-mem-bw}BINOBJ:%.o=%.d}
${DIR-mem-bw}BINEXE	:=		${${DIR-mem-bw}BINOBJ:${BUILD}%.o=${BIN}%.exe}
${DIR-mem-bw}BINASM	:=		${${DIR-mem-bw}BINOBJ:${BUILD}%.o=${DEBUG}%.s}
################## DO NOT MODIFY ################
###############################################################################
#				STEP 4
#DIRECTORY-SPECIFIC TEST FILES
#	Speicify all the test files. All test files must be CPP files. But when
#  listing the them in ${DIR-mem-bw}TST, do NOT write the .cpp extension. For example:
#  if one wishes to add test-mytest.cpp, he should write:
#
#  		${DIR-mem-bw}TST:=test-mytest
#
${DIR-mem-bw}TST	:=		test-sumcopy time-sumcopy
${BUILD}/test-sumcopy.exe: ${BUILD}/test-sumcopy.o ${BUILD}/Utils.o ${BUILD}/sumcopy.o
${BUILD}/time-sumcopy.exe: ${BUILD}/time-sumcopy.o ${BUILD}/Utils.o ${BUILD}/sumcopy.o
################## DO NOT MODIFY ################
${DIR-mem-bw}TSTCPP	:=		${${DIR-mem-bw}TST:%=${DIR-mem-bw}/%.cpp}
${DIR-mem-bw}TSTOBJ	:=		${${DIR-mem-bw}TSTCPP:${DIR-mem-bw}%.cpp=${BUILD}%.o}
${DIR-mem-bw}TSTDEP	:=		${${DIR-mem-bw}TSTOBJ:%.o=%.d}
${DIR-mem-bw}TSTEXE	:=		${${DIR-mem-bw}TSTOBJ:%.o=%.exe}
${DIR-mem-bw}TSTASM	:=		${${DIR-mem-bw}TSTOBJ:${BUILD}%.o=${DEBUG}%.s}
SRCFILES	:=		${SRCFILES} ${${DIR-mem-bw}CFILES} ${${DIR-mem-bw}CPPFILES} ${${DIR-mem-bw}TSTCPP} ${${DIR-mem-bw}BINCPP}
DEPFILES	:=		${DEPFILES} ${${DIR-mem-bw}DEPFILES} ${${DIR-mem-bw}TSTDEP} ${${DIR-mem-bw}BINDEP}
################## DO NOT MODIFY ################
###############################################################################
#				STEP 5
#DIRECTORY-SPECIFIC COMPILING AND LINKING OPTIONS
#	Options specified here are used in this directory. By default, all 
#  builds use the same options. When different compiling and/or linking options 
#  need to be assigned to different targets, the programmer needs to list all
#  the speical target-prerequisite dependencies manually.
#  	By default, the local options inherits the corresponding global ones 
#  from the makevars.mk in the root directory. If one wishes to add any 
#  additional options that are specific to this very directory, add them after 
#  the global ones. For example:
# 	 	${DIR-mem-bw}CFLAGS	:=${CFLAGS} [directory-specific options]
#  	Usually, ${DIR-mem-bw}INCS and ${DIR-mem-bw}LIBS should not need to be modified if
#  the build in this directory does not require some extra libraries and/or 
#  hearder files. But in case it did, free at ease to modify these two 
#  variables.
${DIR-mem-bw}CFLAGS 	:=${CFLAGS}
${DIR-mem-bw}CXXFLAGS	:=${CXXFLAGS}
${DIR-mem-bw}INCS		:=${INCS}
#${DIR-mem-bw}LIBS		:=${LIBS} 
###############################################################################
#				STEP 6
#	Write whatever dependencies here:



###############################################################################
###############################################################################
###############################################################################
#	Congratulations! You have completed everything you need to do to build
#  this directory. You do not need to modify this file unless some C and/or
#  CPP source files are added, removed, or renamed. In that case, just go over
#  STEP 1-6 again and it is done!
###############################################################################
###############################################################################
###############################################################################
#				WANRING
#  Please do not modify the following part if you are not 100% sure about it.
#  The design of this file is that one only needs to modify the part above.
#  If you find you need to modify any of the parts below, be very careful!
#				WANRING
###############################################################################
###############################################################################
############################################################################### 
#DIR-mem-bwECTORY-SPECIFIC PATTERN RULES
##  C++ linkage at the top level
#${BIN}/%.exe: ${BUILD}/%.o 
	#@echo Linking  "${B_RED}$@${NONE}"...
	#@${CXX} -o $@ ${filter %.o,$^} ${${DIR-mem-bw}LIBS} 
#${BUILD}/%.exe: ${BUILD}/%.o 
	#@echo Linking  "${B_RED}$@${NONE}"...
	#@${CXX} -o $@ ${filter %.o,$^} ${${DIR-mem-bw}LIBS} 
#  C++ sources
${BUILD}/%.o: ${DIR-mem-bw}/%.cpp
	@echo Compiling "${MAGENTA}$@${NONE}"...
	@${CXX} -o $@ -c $< ${${DIR-mem-bw}CXXFLAGS} ${${DIR-mem-bw}INCS}
${DEBUG}/%.s: ${DIR-mem-bw}/%.cpp
	@echo Generating "${CYAN}$@${NONE}"...
	@${CXX} -o $@ $< ${ASMFLAGS} ${${DIR-mem-bw}CXXFLAGS} ${${DIR-mem-bw}INCS} 
#  C sources
${BUILD}/%.o: ${DIR-mem-bw}/%.c
	@echo Compiling "${MAGENTA}$@${NONE}"...
	@${CC} -o $@ -c $< ${${DIR-mem-bw}CFLAGS} ${${DIR-mem-bw}INCS}
${DEBUG}/%.s: ${DIR-mem-bw}/%.c
	@echo Generating "${CYAN}$@${NONE}"...
	@${CC} -o $@ $< ${ASMFLAGS} ${${DIR-mem-bw}CFLAGS} ${${DIR-mem-bw}INCS} 
#DIR-mem-bwECTORY-SPECIFIC PHONY TARGETS
.PHONY: ${DIR-mem-bw}-all ${DIR-mem-bw}-test ${DIR-mem-bw}-asm ${DIR-mem-bw}-list
TARGET_ALL	:=${TARGET_ALL} ${DIR-mem-bw}-all
TARGET_TEST	:=${TARGET_TEST} ${DIR-mem-bw}-test
TARGET_ASM	:=${TARGET_ASM} ${DIR-mem-bw}-asm
TARGET_LIST	:=${TARGET_LIST} ${DIR-mem-bw}-list
${DIR-mem-bw}-all: ${${DIR-mem-bw}OBJFILES} ${${DIR-mem-bw}BINEXE}
	@echo Finished building "${B_BLUE}$@${NONE}".
${DIR-mem-bw}-test: ${${DIR-mem-bw}TSTEXE}
	@echo Finished building "${B_BLUE}$@${NONE}".  
${DIR-mem-bw}-asm: ${${DIR-mem-bw}ASMFILES} ${${DIR-mem-bw}TSTASM}
	@echo Finished generating "${B_BLUE}$@${NONE}".  
${DIR-mem-bw}-list:
	@echo \#\#\#\#\#\#\#\#"${B_BROWN}BEGIN $@${NONE}"\#\#\#\#\#\#\#\#
	@echo "${BROWN}CFILES${NONE}":${${DIR-mem-bw}CFILES}
	@echo "${BROWN}CPPFILES${NONE}":${${DIR-mem-bw}CPPFILES}
	@echo "${BROWN}OBJFILES${NONE}":${${DIR-mem-bw}OBJFILES}
	@echo "${BROWN}DEPFILES${NONE}":${${DIR-mem-bw}DEPFILES}
	@echo "${BROWN}ASMFILES${NONE}":${${DIR-mem-bw}ASMFILES}
	@echo "${BROWN}TSTCPP${NONE}":${${DIR-mem-bw}TSTCPP}
	@echo "${BROWN}TSTOBJ${NONE}":${${DIR-mem-bw}TSTOBJ}
	@echo "${BROWN}TSTDEP${NONE}":${${DIR-mem-bw}TSTDEP}
	@echo "${BROWN}TSTEXE${NONE}":${${DIR-mem-bw}TSTEXE}
	@echo "${BROWN}TSTASM${NONE}":${${DIR-mem-bw}TSTASM} 
	@echo "${BROWN}BINCPP${NONE}":${${DIR-mem-bw}BINCPP}
	@echo "${BROWN}BINOBJ${NONE}":${${DIR-mem-bw}BINOBJ}
	@echo "${BROWN}BINDEP${NONE}":${${DIR-mem-bw}BINDEP}
	@echo "${BROWN}BINEXE${NONE}":${${DIR-mem-bw}BINEXE}
	@echo "${BROWN}BINASM${NONE}":${${DIR-mem-bw}BINASM} 
	@echo \#\#\#\#\#\#\#\#"${B_BROWN}END $@${NONE}"\#\#\#\#\#\#\#\#
